### PR TITLE
Fix ``__setstate__`` interning when ``state`` parameter is not a built-in dict

### LINKED ISSUE #60: Persistent.__setstate__ C SILENTLY fails on non-builtin dict
Key interning introduced in https://github.com/zopefoundation/persistent/commit/7bd85c189ae17be514f4989bfb8f79f4d8013943 makes ```__setstate__``` SILENTLY fail when a  non-builtin dict is passed as state.

See https://github.com/agroszer/persistent/commit/1c1cebaf79914420a9de61e55fb72a75981965b2 how to provoke that.

- is there any constraint that ```state``` must be a builtin dict ?
- the C and python implementation differs, because the python one does not fail
- a major issue is that it silently fails, just not setting attributes and returning

### PR DESCRIPTION
**Pull request by agroszer**
fixes #60

### CODE REVIEW

File: persistent/cPersistence.c [hunk 1]
```diff
@@ -609,17 +611,41 @@ pickle___setstate__(PyObject *self, PyObject *state)
...
+                d_key = PyTuple_GetItem(item, 0);
+                d_value = PyTuple_GetItem(item, 1);
+
+                if (NATIVE_CHECK_EXACT(d_key)) {
+                    Py_INCREF(d_key);
+                    INTERN_INPLACE(&d_key);
+                    Py_DECREF(d_key);
+                }
+                if (PyObject_SetItem(*dict, d_key, d_value) < 0)
+                    return NULL;
```
Comment (mgedmin) [inline persistent/cPersistence.c]: I'm not familiar with the CPython C API, so to check for possible refcounting errors I ran the test suite in a loop (zope-testrunner --repeat 100) and saw no memory usage increase.

IOW, LGTM!

File: persistent/cPersistence.c [hunk 2]
```diff
@@ -609,17 +611,41 @@ pickle___setstate__(PyObject *self, PyObject *state)
...
+            }
+        }
+        else
+        {
+            /* can happen that not a built-in dict is passed as state
+               fall back to iterating over items, instead of silently
+               failing with PyDict_Next */
+            items = PyMapping_Items(state);
```
Comment (stephan-hof) [inline persistent/cPersistence.c]: Please check for NULL. Which means an exception has been raised.
Take care to call Py_DECREF on `items` when they are not used. Otherwise memory leak.

File: persistent/cPersistence.c [hunk 3]
```diff
@@ -609,17 +611,41 @@ pickle___setstate__(PyObject *self, PyObject *state)
...
+            len = PySequence_Size(items);
```
Comment (stephan-hof) [inline persistent/cPersistence.c]: I think its better to check `-1` here which signals an error. If that is the case return NULL (and call decref on items).
This re raises the exception from `PySequence_Size` to the caller.

File: persistent/cPersistence.c [hunk 4]
```diff
@@ -609,17 +611,41 @@ pickle___setstate__(PyObject *self, PyObject *state)
...
+            for ( i=0; i<len; ++i ) {
+                PyObject *item = PySequence_GetItem(items, i);
```
Comment (stephan-hof) [inline persistent/cPersistence.c]: Call Py_DECREF on `item` when not used anymore. Otherwise memory leak.
Also check for NULL in case of errors.

File: persistent/cPersistence.c [hunk 5]
```diff
@@ -609,17 +611,41 @@ pickle___setstate__(PyObject *self, PyObject *state)
...
+                d_key = PyTuple_GetItem(item, 0);
+                d_value = PyTuple_GetItem(item, 1);
+
```
Comment (stephan-hof) [inline persistent/cPersistence.c]: Check `d_key` and `d_value` for NULL (for example if item is not a tuple) and reraise it to the caller by returning NULL.
Take care to decref `item` and `items` in that case

File: persistent/cPersistence.c (hunk 1 above)
Comment (stephan-hof) [inline persistent/cPersistence.c]: In this error case decref `item` and `items` otherwise they are leaking.

Comment (mgedmin) [inline persistent/cPersistence.c]: (In retrospect, 100 iterations may not be enough to expose a sufficiently small leak, if I'm just looking at the overall memory usage in megabytes.)

**Comment by agroszer** [comment]
@stephan-hof does it look good now?

File: persistent/cPersistence.c [hunk 6]
```diff
@@ -632,20 +632,47 @@ pickle___setstate__(PyObject *self, PyObject *state)
...
             len = PySequence_Size(items);
+            if (len < 0)
+            {
+                Py_DECREF(items);
+                return NULL;
+            }
             for ( i=0; i<len; ++i ) {
                 PyObject *item = PySequence_GetItem(items, i);
+                if (item == NULL)
+                    return NULL;
```
Comment (stephan-hof) [inline persistent/cPersistence.c]: Please decref `items` otherwise they leak.

File: persistent/cPersistence.c [hunk 7]
```diff
@@ -632,20 +632,47 @@ pickle___setstate__(PyObject *self, PyObject *state)
...
+                if (d_key == NULL)
+                {
+                    Py_DECREF(item);
+                    Py_DECREF(items);
+                    return NULL;
+                }
                 d_value = PyTuple_GetItem(item, 1);
+                if (d_value == NULL)
+                {
+                    Py_DECREF(d_key);
```
Comment (stephan-hof) [inline persistent/cPersistence.c]: No need to decref `d_key` here, because `PyTuple_GetItem` returns a borrowed reference. Not a new one.

**Comment by agroszer** [comment]
@jimfulton or @tseaver release please
