### PR TITLE
Use unsigned constants for second arithmetic in C timestamp

### LINKED ISSUE #86: persistent.tests.test_timestamp.PyAndCComparisonTests.test_strs_equal fails
```
[   15s] ======================================================================
[   15s] FAIL: test_strs_equal (persistent.tests.test_timestamp.PyAndCComparisonTests)
[   15s] ----------------------------------------------------------------------
[   15s] Traceback (most recent call last):
[   15s]   File "/home/abuild/rpmbuild/BUILD/persistent-4.2.4.2/persistent/tests/test_timestamp.py", line 253, in test_strs_equal
[   15s]     self.assertEqual(str(c), str(py))
[   15s] AssertionError: '2008-12-22 15:20:-11.700000' != '2008-12-22 15:20:48.300000'
[   15s] - 2008-12-22 15:20:-11.700000
[   15s] ?                  ^^^ ^
[   15s] + 2008-12-22 15:20:48.300000
[   15s] ?                  ^^ ^
```
[Build log](https://github.com/zopefoundation/persistent/files/2287337/osc-build-log.txt)

This is running on completely normal run-of-the-mill Lenovo Thinkpad T480 with openSUSE Tumbleweed, so of course it is x86_64 architecture. Using persistent-4.2.4.2.tar.gz.

Replacing my comment in #41.

### PR DESCRIPTION
**Pull request by jamadden**
This *might* fix #86? (*waves hands* by avoiding mixing signed and unsigned operations)

I personally find that it makes the data derivation/reconstruction more clear by making the powers-of-two factors more obvious. (The two smaller values were clear to me, but without punctuation it wasn't immediately obvious to me that 16777216 = 16,777,216 = 0x1000000 = 2^24.)

(Tested locally on 64-bit, relying on Appveyor CI for 32-bit tests.)

### CODE REVIEW

File: persistent/_timestamp.c [hunk 1]
```diff
@@ -185,8 +185,8 @@ TimeStamp_unpack(TimeStamp *self, TimeStampParts *p)
 {
     unsigned long v;
 
-    v = (self->data[0] * 16777216 + self->data[1] * 65536
-       + self->data[2] * 256 + self->data[3]);
+    v = (self->data[0] * 0x1000000 + self->data[1] * 0x10000
+       + self->data[2] * 0x100 + self->data[3]);
```
Comment (tseaver) [inline persistent/_timestamp.c]: Can we name all these constants in order to avoid typos?  (the majyk ones below, too).

Comment (jamadden) [reply persistent/_timestamp.c]: Any name suggestions? I wasn't doing any better than MASK_24 and the like, which didn't seem like much of an improvement.

Comment (jamadden) [reply persistent/_timestamp.c]: I think I may have it now. commit forthcoming.

Comment (jamadden) [reply persistent/_timestamp.c]: How about this?

File: persistent/_timestamp.c [hunk 2]
```diff
@@ -27,9 +27,40 @@ static char TimeStampModule_doc[] =
 "$Id$\n";
 
 
+
+#define SCONV ((double)60) / ((double)(0x10000)) / ((double)(0x10000))
```
Comment (tseaver) [inline persistent/_timestamp.c]: Ugh!  That name doesn't help with semantics at all.

File: persistent/_timestamp.c [hunk 3]
```diff
@@ -27,9 +27,40 @@ static char TimeStampModule_doc[] =
...
+#define TS_BASE_YEAR 1900
+#define TS_MINUTES_PER_DAY 1440
+/* We pretend there are always 31 days in a month; this has us using
+   372 days in a year in some calculations */
+#define TS_DAYS_PER_MONTH 31
+#define TS_MONTHS_PER_YEAR 12
+#define TS_MINUTES_PER_MONTH (TS_DAYS_PER_MONTH * TS_MINUTES_PER_DAY)
+#define TS_MINUTES_PER_YEAR (TS_MINUTES_PER_MONTH * TS_MONTHS_PER_YEAR)
+
+#define TS_PACK_UNSIGNED_INTO_BYTES(v, bytes) do { \
```
Comment (tseaver) [inline persistent/_timestamp.c]: Pack unsigned *what* into bytes?

File: persistent/_timestamp.c [hunk 4]
```diff
@@ -27,9 +27,40 @@ static char TimeStampModule_doc[] =
...
+    *(bytes) = v / 0x1000000;                      \
+    *(bytes + 1) = (v % 0x1000000) / 0x10000;      \
+    *(bytes + 2) = (v % 0x10000) / 0x100;          \
+    *(bytes + 3) = v % 0x100;                      \
+} while (0)
+
+#define TS_UNPACK_UNSIGNED_FROM_BYTES(bytes) (*(bytes) * 0x1000000 + *(bytes + 1) * 0x10000 + *(bytes + 2) * 0x100 + *(bytes + 3))
```
Comment (tseaver) [inline persistent/_timestamp.c]: Likewise here:  what is the semantic of the return value?

File: persistent/_timestamp.c (hunk 3 above)
Comment (jamadden) [reply persistent/_timestamp.c]: The given *bytes*. I assume you're looking for something like 'INTO_4_BYTES'?

File: persistent/_timestamp.c (hunk 4 above)
Comment (jamadden) [reply persistent/_timestamp.c]: It's the inverse of `TS_PACK_UNSIGNED_INTO_BYTES`. I documented that in the *TimeStamp* comment, but I can document it here as well.

File: persistent/_timestamp.c (hunk 3 above)
Comment (tseaver) [reply persistent/_timestamp.c]: What are the semantics of `v`, as we use it?

File: persistent/_timestamp.c (hunk 2 above)
Comment (jamadden) [reply persistent/_timestamp.c]: Renamed, and documented with concrete values.

File: persistent/_timestamp.c (hunk 4 above)
Comment (tseaver) [reply persistent/_timestamp.c]: What are the semantics of the returned value?  We are using it for something specific, not random unsigned (what length?) values.

File: persistent/_timestamp.c (hunk 3 above)
Comment (jamadden) [reply persistent/_timestamp.c]: Documentation added.

File: persistent/_timestamp.c (hunk 4 above)
Comment (jamadden) [reply persistent/_timestamp.c]: Fair question. Hopefully the docs I added address that.

File: persistent/_timestamp.c [hunk 5]
```diff
@@ -27,8 +27,15 @@ static char TimeStampModule_doc[] =
...
-#define SCONV ((double)60) / ((double)(0x10000)) / ((double)(0x10000))
+/* A magic constant having the value 0.000000013969839. When an
+   number of seconds between 0 and 59 is *divided* by this number, we get
+   a number between 0 (for 0), 71582786 (for 1) and 4223384393 (for 59),
+   all of which can be represented in a 32-bit unsigned integer, suitable
+   for packing into 4 bytes using `TS_PACK_UNSIGNED_INTO_BYTES`.
+   To get (close to) the original seconds back, use
+   `TS_UNPACK_UNSIGNED_FROM_BYTES` and *multiply* by this number.
+ */
+#define TS_SECOND_BYTES_BIAS ((double)60) / ((double)(0x10000)) / ((double)(0x10000))
```
Comment (tseaver) [inline persistent/_timestamp.c]: Thanks, this helps a bunch!

Comment (jamadden) [reply persistent/_timestamp.c]: I feel like I learned a lot in the process of documenting!

(Ooops, there's still an SCONV  in the Python implementation, I should rename that.)

File: persistent/_timestamp.c (hunk 4 above)
Comment (jamadden) [reply persistent/_timestamp.c]: And I changed the name from `_UNSIGNED_` into `_UINT32_` to be more specific about the expected range of the input/output.

**Comment by jamadden** [comment]
Thanks! I appreciate the good feedback on this.
